name: carbon_emission_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.9
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
